export default function TermsPage() {
  return (
    <main className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
      <div className="space-y-8 rounded-3xl border border-white/10 bg-white/5 p-10 shadow-2xl shadow-black/20">
        <p className="text-sm uppercase tracking-[0.3em] text-mist/60">Last Updated January 2026</p>
        <h1 className="text-4xl font-semibold text-mist">Terms of Service</h1>
        <div className="space-y-6 text-mist/80">
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-mist">Overview</h2>
            <p>
              EcoTrace is provided as a personal carbon footprint estimator. The estimates are based on publicly available emission factors and should be used for awareness and planning only.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-mist">Disclaimer</h2>
            <p>
              Carbon estimates generated by EcoTrace are illustrative and are not official offset calculations. They are not intended to replace professional audits or verified carbon accounting services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-mist">Liability</h2>
            <p>
              EcoTrace is provided &quot;as is&quot; without warranties of accuracy or completeness. We are not responsible for decisions made using the platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-mist">User conduct</h2>
            <p>
              By using EcoTrace, you agree to provide accurate information and not to misuse the service for fraudulent or misleading purposes.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
